controllers/OrderController.php
<?php

namespace app\controllers;

use app\models\forms\Order;
use app\models\ProductOrder;
use app\models\search\ActiveOrdersSearch;
use app\models\search\DoneOrdersSearch;
use app\models\search\NewOrdersSearch;
use app\models\search\OutdatedOrdersSearch;
use app\services\EmailService;
use Exception;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UnprocessableEntityHttpException;

/**
 * Class OrderController
 * @package app\controllers
 */
class OrderController extends Controller
{
    /**
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = Yii::createObject(OutdatedOrdersSearch::class);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string
     */
    public function actionActive()
    {
        $searchModel = Yii::createObject(ActiveOrdersSearch::class);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('active', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string
     */
    public function actionNew()
    {
        $searchModel = Yii::createObject(NewOrdersSearch::class);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('new', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string
     */
    public function actionDone()
    {
        $searchModel = Yii::createObject(DoneOrdersSearch::class);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('done', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string|Response
     */
    public function actionCreate()
    {
        $model = new Order();
        $translaction = Yii::$app->db->beginTransaction();
        try {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                $this>$this->saveRelations($model);
                $translaction->commit();
                Yii::$app->session->addFlash('success', 'Record updated');
                return $this->redirect(['update', 'id' => $model->primaryKey]);
            }
        } catch (Exception $ex) {
            $translaction->rollBack();
        }
        return $this->render('create', [
            'model' => $model
        ]);
    }

    /**
     * @param int $id
     * @return string|Response
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $translaction = Yii::$app->db->beginTransaction();
        try {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                $this>$this->saveRelations($model);
                if ($model->status == Order::STATUS_DONE && !$model->email_sent) {
                    $model->email_sent = true;
                    $model->update(true, ['email_sent']);
                    $this->sendEmail($model);
                }
                $translaction->commit();
                Yii::$app->session->addFlash('success', 'Record updated');
                return $this->redirect(['update', 'id' => $model->primaryKey]);
            }
        } catch (Exception $ex) {
            $translaction->rollBack();
        }

        return $this->render('update', [
            'model' => $model,
            'totalPrice' => array_sum(array_map(function (ProductOrder $productOrder) {
                return $productOrder->price;
            }, $model->loadedProduts))
        ]);
    }

    /**
     * @param int $id
     * @return Response
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    public function actionChangeStatus()
    {
        if (!Yii::$app->request->isAjax) {
            throw new ForbiddenHttpException;
        }

        $post = Yii::$app->request->post('Order');
        if ($post) {
            $model = $this->findModel(ArrayHelper::getValue($post, 'id'));
            $model->status = ArrayHelper::getValue($post, 'status');
            if ($model->update(true, ['status']) === false) {
                throw new UnprocessableEntityHttpException($model->getFirstError('status'));
            }

            if ($model->status == Order::STATUS_DONE && !$model->email_sent) {
                $model->email_sent = true;
                $model->update(true, ['email_sent']);
                $this->sendEmail($model);
            }
            return true;
        }
        return false;
    }

    /**
     * @param int $id
     * @return Order
     * @throws NotFoundHttpException
     */
    private function findModel($id)
    {
        $model = Order::findOne($id);
        if ($model === null) {
            throw new NotFoundHttpException;
        }
        return $model;
    }

    /**
     * @param Order $model
     */
    private function sendEmail(Order $model)
    {
        $service = new EmailService();
        $service->sendOrderEmail($model);
    }

    /**
     * @param Order $model
     */
    private function saveRelations(Order $model)
    {
        ProductOrder::deleteAll([
            'order_id' => $model->primaryKey
        ]);
        foreach ($model->loadedProduts as $product) {
            $product->order_id = $model->primaryKey;
            $product->price = $product->quantity * $product->product->price;
            $product->save();
        }
    }
}

controllers/PartnerController.php
<?php

namespace app\controllers;

use app\models\Partner;
use app\models\search\PartnerSearch;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * Class PartnerController
 * @package app\controllers
 */
class PartnerController extends Controller
{
    /**
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = Yii::createObject(PartnerSearch::class);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string|Response
     */
    public function actionCreate()
    {
        $model = new Partner();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->addFlash('success', 'Record created');
            return $this->redirect(['index']);
        }
        return $this->render('create', [
            'model' => $model
        ]);
    }

    /**
     * @param int $id
     * @return string|Response
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->addFlash('success', 'Record updated');
            return $this->redirect(['index']);
        }
        return $this->render('update', [
            'model' => $model
        ]);
    }

    /**
     * @param int $id
     * @return Response
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    /**
     * @param int $id
     * @return Partner
     * @throws NotFoundHttpException
     */
    private function findModel($id)
    {
        $model = Partner::findOne($id);
        if ($model === null) {
            throw new NotFoundHttpException;
        }
        return $model;
    }
}

controllers/ProductController.php
<?php

namespace app\controllers;

use app\models\Product;
use app\models\search\ProductSearch;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UnprocessableEntityHttpException;

/**
 * Class ProductController
 * @package app\controllers
 */
class ProductController extends Controller
{
    /**
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = Yii::createObject(ProductSearch::class);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string|Response
     */
    public function actionCreate()
    {
        $model = new Product();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->addFlash('success', 'Record created');
            return $this->redirect(['index']);
        }
        return $this->render('create', [
            'model' => $model
        ]);
    }

    /**
     * @param int $id
     * @return string|Response
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->addFlash('success', 'Record updated');
            return $this->redirect(['index']);
        }
        return $this->render('update', [
            'model' => $model
        ]);
    }

    /**
     * @param int $id
     * @return Response
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    /**
     * @return float
     * @throws ForbiddenHttpException
     * @throws UnprocessableEntityHttpException
     */
    public function actionChangePrice()
    {
        if (!Yii::$app->request->isAjax) {
            throw new ForbiddenHttpException;
        }

        $product = Yii::$app->request->post('Product');
        if ($product) {
            $model = $this->findModel(ArrayHelper::getValue($product, 'id'));
            $model->price = ArrayHelper::getValue($product, 'price');
            if ($model->update(true, ['price']) === false) {
                throw new UnprocessableEntityHttpException($model->getFirstError('price'));
            }
            return true;
        }
        return false;
    }

    /**
     * @param int $id
     * @return Product
     * @throws NotFoundHttpException
     */
    private function findModel($id)
    {
        $model = Product::findOne($id);
        if ($model === null) {
            throw new NotFoundHttpException;
        }
        return $model;
    }
}

controllers/VendorController.php
<?php

namespace app\controllers;

use app\models\search\VendorSearch;
use app\models\Vendor;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * Class VendorController
 * @package app\controllers
 */
class VendorController extends Controller
{
    /**
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = Yii::createObject(VendorSearch::class);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string|Response
     */
    public function actionCreate()
    {
        $model = new Vendor();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->addFlash('success', 'Record created');
            return $this->redirect(['index']);
        }
        return $this->render('create', [
            'model' => $model
        ]);
    }

    /**
     * @param int $id
     * @return string|Response
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->addFlash('success', 'Record updated');
            return $this->redirect(['index']);
        }
        return $this->render('update', [
            'model' => $model
        ]);
    }

    /**
     * @param int $id
     * @return Response
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    /**
     * @param int $id
     * @return Vendor
     * @throws NotFoundHttpException
     */
    private function findModel($id)
    {
        $model = Vendor::findOne($id);
        if ($model === null) {
            throw new NotFoundHttpException;
        }
        return $model;
    }
}

views/layouts/empty.php
<?php

use app\assets\AppAsset;
use yii\helpers\Html;
use yii\web\View;

/**
 * @var View $this
 * @var string $content
 */

AppAsset::register($this);

$this->beginPage();
?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="<?= Yii::$app->charset ?>">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition">
<?php $this->beginBody(); ?>
<?= $content ?>
<?php $this->endBody(); ?>
</body>
</html>
<?php
$this->endPage();

views/layouts/login.php
<?php

use app\assets\AppAsset;
use yii\helpers\Html;
use yii\web\View;

/**
 * @var View $this
 * @var string $content
 */

AppAsset::register($this);

$this->beginPage();
?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="<?= Yii::$app->charset ?>">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition login-page">
<?php $this->beginBody(); ?>
<?= $content ?>
<?php $this->endBody(); ?>
</body>
</html>
<?php
$this->endPage();

views/layouts/main.php
<?php

use app\assets\AdminLTEAsset;
use app\assets\AppAsset;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;
use yii\widgets\Menu;

/**
 * @var string $content
 */

AppAsset::register($this);
$adminLteAsset = AdminLTEAsset::register($this);

$this->beginPage();
?>
    <!DOCTYPE html>
    <html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="<?= Yii::$app->charset ?>">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="hold-transition skin-blue-light sidebar-mini">
    <?php $this->beginBody(); ?>
    <div class="wrapper">
        <header class="main-header">

            <!-- Logo -->
            <a data-toggle="offcanvas" role="button" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><i class="fa fa-bars"></i></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><?= Yii::t('app', 'Store') ?></span>
            </a>

            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <?= Html::img($adminLteAsset->baseUrl . '/img/avatar5.png', ['class' => 'user-image']) ?>
                                <span class="hidden-xs"><?= Yii::$app->user->identity->email ?></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <?= Html::img($adminLteAsset->baseUrl . '/img/avatar5.png', ['class' => 'img-circle']) ?>
                                    <p>
                                        <?= Yii::$app->user->identity->email ?>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-right">
                                        <a href="<?=Url::to(['/site/logout'])?>" class="btn btn-default btn-flat">Logout</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>

            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <?= Menu::widget([
                    'encodeLabels' => false,
                    'options' => [
                        'class' => 'sidebar-menu',
                    ],
                    'activateParents' => true,
                    'submenuTemplate' => "\n<ul class='treeview-menu'>\n{items}\n</ul>\n",
                    'items' => [
                        [
                            'label' => '<i class="fa fa-user"></i> <span>Vendors</span>',
                            'url' => ['/vendor/index'],
                            'active' => Yii::$app->controller->id === 'vendor',
                        ],
                        [
                            'label' => '<i class="fa fa-database"></i> <span>Partners</span>',
                            'url' => ['/partner/index'],
                            'active' => Yii::$app->controller->id === 'partner',
                        ],
                        [
                            'label' => '<i class="fa fa-envelope"></i> <span>Products</span>',
                            'url' => ['/product/index'],
                            'active' => Yii::$app->controller->id === 'product',
                        ],
                        [
                            'label' => '<i class="fa fa-flag"></i> <span>Orders</span>',
                            'url' => ['/order/index'],
                            'active' => Yii::$app->controller->id === 'order',
                        ],
                    ],
                ])?>
            </section>
            <!-- /.sidebar -->
        </aside>
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <?php if (isset($this->params['breadcrumbs'])): ?>
                    <?= Breadcrumbs::widget([
                        'options' => [
                            'class' => 'breadcrumb',
                        ],
                        'encodeLabels' => false,
                        'homeLink' => [
                            'label' => '<i class="fa fa-dashboard"></i> ' . Yii::t('app', 'Store'),
                            'url' => ['/site/index'],
                        ],
                        'links' => $this->params['breadcrumbs'],
                    ]) ?>
                <?php endif; ?>
            </section>

            <!-- Main content -->
            <section class="content" style="padding-top: 35px;">
                <?php
                if (count(Yii::$app->session->getAllFlashes())) {
                    foreach (Yii::$app->session->getAllFlashes() as $key => $messages) {
                        foreach ($messages as $message) {
                            echo '<div class="callout callout-' . $key . '"><p>' . $message . '</p></div>';
                        }
                    }
                }
                ?>
                <?= $content ?>
            </section>
        </div>
    </div>
    <?php $this->endBody(); ?>
    </body>
    </html>
<?php
$this->endPage();