models/Order.php
<?php

namespace app\models;

use app\models\query\OrderQuery;
use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

/**
 * @property int $id
 * @property int $partner_id
 * @property int $status
 * @property string $client_email
 * @property string|null $delivery_at
 * @property string $created_at
 * @property string $updated_at
 * @property bool $email_sent
 *
 * @property-read Partner $partner
 * @property-read ProductOrder[] $productOrders
 * @property-read string|null orderStatus
 */
class Order extends ActiveRecord
{
    const STATUS_NEW = 0;
    const STATUS_CONFIRMED = 10;
    const STATUS_DONE = 20;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%order}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_NEW],
            ['client_email', 'trim'],
            ['client_email', 'email'],
            [['partner_id', 'client_email', 'delivery_at'], 'required'],
            [['partner_id', 'status'], 'integer'],
            [['delivery_at'], 'safe'],
            [['email_sent'], 'boolean'],
            [['delivery_at'], 'filter', 'filter' => function () {
                return date('Y-m-d H:i:s', strtotime($this->delivery_at));
            }],
            [['client_email'], 'string', 'max' => 255],
            [['partner_id'], 'exist', 'skipOnError' => true, 'targetRelation' => 'partner'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'partner_id' => Yii::t('app', 'Partner'),
            'status' => Yii::t('app', 'Status'),
            'client_email' => Yii::t('app', 'Client email'),
            'delivery_at' => Yii::t('app', 'Delivery date'),
            'created_at' => Yii::t('app', 'Create date'),
            'updated_at' => Yii::t('app', 'Update date'),
        ];
    }

    /**
     * @return array
     */
    public static function getStatusList()
    {
        return [
            self::STATUS_NEW => Yii::t('app', 'New'),
            self::STATUS_CONFIRMED => Yii::t('app', 'Confirmed'),
            self::STATUS_DONE => Yii::t('app', 'Done'),
        ];
    }

    /**
     * @return string|null
     */
    public function getOrderStatus()
    {
        return ArrayHelper::getValue(self::getStatusList(), $this->status);
    }

    /**
     * @return ActiveQuery
     */
    public function getPartner()
    {
        return $this->hasOne(Partner::class, ['id' => 'partner_id']);
    }

    /**
     * @return ActiveQuery
     */
    public function getProductOrders()
    {
        return $this->hasMany(ProductOrder::class, ['order_id' => 'id']);
    }

    /**
     * @return OrderQuery
     */
    public static function find()
    {
        return new OrderQuery(get_called_class());
    }
}

controllers/OrderController.php
<?php

namespace app\controllers;

use app\models\forms\Order;
use app\models\ProductOrder;
use app\models\search\ActiveOrdersSearch;
use app\models\search\DoneOrdersSearch;
use app\models\search\NewOrdersSearch;
use app\models\search\OutdatedOrdersSearch;
use app\services\EmailService;
use Exception;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UnprocessableEntityHttpException;

/**
 * Class OrderController
 * @package app\controllers
 */
class OrderController extends Controller
{
    /**
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = Yii::createObject(OutdatedOrdersSearch::class);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string
     */
    public function actionActive()
    {
        $searchModel = Yii::createObject(ActiveOrdersSearch::class);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('active', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string
     */
    public function actionNew()
    {
        $searchModel = Yii::createObject(NewOrdersSearch::class);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('new', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string
     */
    public function actionDone()
    {
        $searchModel = Yii::createObject(DoneOrdersSearch::class);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('done', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string|Response
     */
    public function actionCreate()
    {
        $model = new Order();
        $translaction = Yii::$app->db->beginTransaction();
        try {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                $this>$this->saveRelations($model);
                $translaction->commit();
                Yii::$app->session->addFlash('success', 'Record updated');
                return $this->redirect(['update', 'id' => $model->primaryKey]);
            }
        } catch (Exception $ex) {
            $translaction->rollBack();
        }
        return $this->render('create', [
            'model' => $model
        ]);
    }

    /**
     * @param int $id
     * @return string|Response
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $translaction = Yii::$app->db->beginTransaction();
        try {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                $this>$this->saveRelations($model);
                if ($model->status == Order::STATUS_DONE && !$model->email_sent) {
                    $model->email_sent = true;
                    $model->update(true, ['email_sent']);
                    $this->sendEmail($model);
                }
                $translaction->commit();
                Yii::$app->session->addFlash('success', 'Record updated');
                return $this->redirect(['update', 'id' => $model->primaryKey]);
            }
        } catch (Exception $ex) {
            $translaction->rollBack();
        }

        return $this->render('update', [
            'model' => $model,
            'totalPrice' => array_sum(array_map(function (ProductOrder $productOrder) {
                return $productOrder->price;
            }, $model->loadedProduts))
        ]);
    }

    /**
     * @param int $id
     * @return Response
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    public function actionChangeStatus()
    {
        if (!Yii::$app->request->isAjax) {
            throw new ForbiddenHttpException;
        }

        $post = Yii::$app->request->post('Order');
        if ($post) {
            $model = $this->findModel(ArrayHelper::getValue($post, 'id'));
            $model->status = ArrayHelper::getValue($post, 'status');
            if ($model->update(true, ['status']) === false) {
                throw new UnprocessableEntityHttpException($model->getFirstError('status'));
            }

            if ($model->status == Order::STATUS_DONE && !$model->email_sent) {
                $model->email_sent = true;
                $model->update(true, ['email_sent']);
                $this->sendEmail($model);
            }
            return true;
        }
        return false;
    }

    /**
     * @param int $id
     * @return Order
     * @throws NotFoundHttpException
     */
    private function findModel($id)
    {
        $model = Order::findOne($id);
        if ($model === null) {
            throw new NotFoundHttpException;
        }
        return $model;
    }

    /**
     * @param Order $model
     */
    private function sendEmail(Order $model)
    {
        $service = new EmailService();
        $service->sendOrderEmail($model);
    }

    /**
     * @param Order $model
     */
    private function saveRelations(Order $model)
    {
        ProductOrder::deleteAll([
            'order_id' => $model->primaryKey
        ]);
        foreach ($model->loadedProduts as $product) {
            $product->order_id = $model->primaryKey;
            $product->price = $product->quantity * $product->product->price;
            $product->save();
        }
    }
}

views/order/_form.php
<?php

use app\models\forms\Order;
use app\models\Partner;
use app\models\Product;
use app\models\ProductOrder;
use backend\modules\templates\models\EmailTemplateView;
use kartik\datetime\DateTimePicker;
use unclead\multipleinput\TabularInput;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\ActiveForm;

/**
 * @var Order $model
 * @var View $this
 */

$form = ActiveForm::begin();
echo $form->field($model, 'partner_id')
    ->dropDownList(ArrayHelper::map(Partner::find()->all(), 'id', 'name'));
echo $form->field($model, 'client_email');
echo $form->field($model, 'status')->dropDownList(Order::getStatusList());
echo $form->field($model, 'delivery_at')->widget(DateTimePicker::class, [
    'pluginOptions' => [
        'todayHighlight' => true
    ]
]);
echo TabularInput::widget([
    'models' => $model->loadedProduts,
    'modelClass' => ProductOrder::class,
    'form' => $form,
    'enableError' => true,
    'cloneButton' => true,
    'columns' => [
        [
            'title' => Yii::t('app', 'Product'),
            'name' => 'product_id',
            'type' => 'dropDownList',
            'items' => ArrayHelper::map(Product::find()->all(), 'id', 'name'),
        ],
        [
            'title' => Yii::t('app', 'Quantity'),
            'name' => 'quantity',
            'defaultValue' => 1,
            'options' => [
                'type' => 'number',
                'class' => 'quantity-field',
                'min' => 1,
                'onkeypress' => 'return event.charCode >= 48',
            ]
        ],
    ]
]);
echo Html::submitButton(Yii::t('app', 'Save'), [
    'class' => 'btn btn-success'
]);
$form->end();

views/order/_grid.php
<?php

use app\models\Order;
use app\models\Partner;
use app\models\search\OutdatedOrdersSearch;
use kartik\date\DatePicker;
use kartik\editable\Editable;
use yii\data\ActiveDataProvider;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/**
 * @var ActiveDataProvider $dataProvider
 * @var OutdatedOrdersSearch $searchModel
 */

 ?>
<div class="box box-primary">
    <div class="box-body">
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                [
                    'attribute' => 'partner_id',
                    'filter' => ArrayHelper::map(Partner::find()->all(), 'id', 'name'),
                    'value' => function (Order $model) {
                        return $model->partner->name;
                    }
                ],
                'client_email',
                [
                    'attribute' => 'status',
                    'format' => 'raw',
                    'filter' => Order::getStatusList(),
                    'value' => function (Order $model) {
                        return Editable::widget([
                            'name' => 'Order[status]',
                            'additionalData' => [
                                'Order[id]' => $model->primaryKey
                            ],
                            'value' => $model->status,
                            'asPopover' => false,
                            'header' => 'Status',
                            'inputType' => Editable::INPUT_DROPDOWN_LIST,
                            'data' => Order::getStatusList(),
                            'options' => [
                                'class' => 'form-control'
                            ],
                            'displayValueConfig'=> Order::getStatusList(),
                            'ajaxSettings' => [
                                'url' => Url::to(['order/change-status']),
                            ]
                        ]);
                    }
                ],
                [
                    'attribute' => 'delivery_at',
                    'filter' => DatePicker::widget([
                        'model' => $searchModel,
                        'attribute' => 'delivery_at',
                        'pluginOptions' => [
                            'format' => 'yyyy-mm-dd',
                            'todayHighlight' => true
                        ]
                    ])
                ],
                [
                    'class' => ActionColumn::class,
                    'headerOptions' => [
                        'width' => 50,
                    ],
                    'template' => '{update} {delete}',
                ],
            ],
        ]) ?>
    </div>
</div>

views/order/_menu.php
<?php

use yii\bootstrap\Tabs;

echo Tabs::widget([
    'options' => [
        'style' => 'margin-top: 25px;'
    ],
    'items' => [
        [
            'label' => Yii::t('app', 'Outdated'),
            'url' => ['index'],
            'active' => Yii::$app->controller->action->id === 'index'
        ],
        [
            'label' => Yii::t('app', 'Active'),
            'url' => ['active'],
            'active' => Yii::$app->controller->action->id === 'active'
        ],
        [
            'label' => Yii::t('app', 'New'),
            'url' => ['new'],
            'active' => Yii::$app->controller->action->id === 'new'
        ],
        [
            'label' => Yii::t('app', 'Done'),
            'url' => ['done'],
            'active' => Yii::$app->controller->action->id === 'done'
        ],
    ],
]);

views/order/active.php
<?php

use app\models\Product;
use app\models\search\ActiveOrdersSearch;
use app\models\Vendor;
use app\models\search\ProductSearch;
use kartik\editable\Editable;
use yii\data\ActiveDataProvider;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var ActiveDataProvider $dataProvider
 * @var ActiveOrdersSearch $searchModel
 */

$this->title = Yii::t('app', 'Active orders');
$this->params['breadcrumbs'][] = $this->title;

?>
<?= Html::a('<i class="fa fa-plus"></i> ' . Yii::t('app', 'Add order'), ['create'], [
    'class' => 'btn btn-success'
]) ?>
<?= $this->render('_menu') ?>
<?= $this->render('_grid', [
    'searchModel' => $searchModel,
    'dataProvider' => $dataProvider,
]) ?>

views/order/create.php
<?php

use app\models\forms\Order;
use yii\web\View;

/**
 * @var Order $model
 * @var View $this
 */


$this->title = Yii::t('app', 'Create order');
$this->params['breadcrumbs'][] = [
    'url' => ['index'],
    'label' => Yii::t('app', 'Orders list')
];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box box-primary">
    <div class="box-body">
        <?= $this->render('_form', [
            'model' => $model
        ]) ?>
    </div>
</div>

views/order/done.php
<?php

use app\models\Product;
use app\models\search\ActiveOrdersSearch;
use app\models\search\DoneOrdersSearch;
use app\models\search\NewOrdersSearch;
use app\models\Vendor;
use app\models\search\ProductSearch;
use kartik\editable\Editable;
use yii\data\ActiveDataProvider;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var ActiveDataProvider $dataProvider
 * @var DoneOrdersSearch $searchModel
 */

$this->title = Yii::t('app', 'Done orders');
$this->params['breadcrumbs'][] = $this->title;

?>
<?= Html::a('<i class="fa fa-plus"></i> ' . Yii::t('app', 'Add order'), ['create'], [
    'class' => 'btn btn-success'
]) ?>
<?= $this->render('_menu') ?>
<?= $this->render('_grid', [
    'searchModel' => $searchModel,
    'dataProvider' => $dataProvider,
]) ?>

views/order/index.php
<?php

use app\models\Product;
use app\models\Vendor;
use app\models\search\ProductSearch;
use kartik\editable\Editable;
use yii\data\ActiveDataProvider;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var ActiveDataProvider $dataProvider
 * @var OutdatedOrdersSearch $searchModel
 */

$this->title = Yii::t('app', 'Outdated orders');
$this->params['breadcrumbs'][] = $this->title;

?>
<?= Html::a('<i class="fa fa-plus"></i> ' . Yii::t('app', 'Add order'), ['create'], [
    'class' => 'btn btn-success'
]) ?>
<?= $this->render('_menu') ?>
<?= $this->render('_grid', [
    'searchModel' => $searchModel,
    'dataProvider' => $dataProvider,
]) ?>

views/order/new.php
<?php

use app\models\Product;
use app\models\search\ActiveOrdersSearch;
use app\models\search\NewOrdersSearch;
use app\models\Vendor;
use app\models\search\ProductSearch;
use kartik\editable\Editable;
use yii\data\ActiveDataProvider;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var ActiveDataProvider $dataProvider
 * @var NewOrdersSearch $searchModel
 */

$this->title = Yii::t('app', 'New orders');
$this->params['breadcrumbs'][] = $this->title;

?>
<?= Html::a('<i class="fa fa-plus"></i> ' . Yii::t('app', 'Add order'), ['create'], [
    'class' => 'btn btn-success'
]) ?>
<?= $this->render('_menu') ?>
<?= $this->render('_grid', [
    'searchModel' => $searchModel,
    'dataProvider' => $dataProvider,
]) ?>

views/order/update.php
<?php

use app\models\forms\Order;
use yii\helpers\ArrayHelper;
use yii\web\View;

/**
 * @var Order $model
 * @var View $this
 * @var float $totalPrice
 */


$this->title = Yii::t('app', 'Update order');
$this->params['breadcrumbs'][] = [
    'url' => ['index'],
    'label' => Yii::t('app', 'Orders list')
];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box box-primary">
    <div class="box-body">
        <?= $this->render('_form', [
            'model' => $model
        ]) ?>
    </div>
</div>
<div class="box box-primary">
    <div class="box-body">
        <?= Yii::t('app', 'Total price: {price}', [
            'price' => Yii::$app->formatter->asCurrency($totalPrice, ArrayHelper::getValue(Yii::$app->params, 'currency'))
        ])?>
    </div>
</div>