models/Product.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * @property int $id
 * @property int $vendor_id
 * @property string $name
 * @property float $price
 * @property string $created_at
 * @property string $updated_at
 *
 * @property-read Vendor $vendor
 */
class Product extends ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%product}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['vendor_id', 'name', 'price'], 'required'],
            [['vendor_id'], 'integer'],
            [['price'], 'number'],
            [['name'], 'string', 'max' => 255],
            [['vendor_id', 'name'], 'unique', 'targetAttribute' => ['vendor_id', 'name']],
            [['vendor_id'], 'exist', 'skipOnError' => true, 'targetRelation' => 'vendor'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'vendor_id' => Yii::t('app', 'Vendor'),
            'name' => Yii::t('app', 'Name'),
            'price' => Yii::t('app', 'Price'),
            'created_at' => Yii::t('app', 'Create date'),
            'updated_at' => Yii::t('app', 'Update date'),
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getVendor()
    {
        return $this->hasOne(Vendor::class, ['id' => 'vendor_id']);
    }
}

controllers/ProductController.php
<?php

namespace app\controllers;

use app\models\Product;
use app\models\search\ProductSearch;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\UnprocessableEntityHttpException;

/**
 * Class ProductController
 * @package app\controllers
 */
class ProductController extends Controller
{
    /**
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = Yii::createObject(ProductSearch::class);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @return string|Response
     */
    public function actionCreate()
    {
        $model = new Product();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->addFlash('success', 'Record created');
            return $this->redirect(['index']);
        }
        return $this->render('create', [
            'model' => $model
        ]);
    }

    /**
     * @param int $id
     * @return string|Response
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->addFlash('success', 'Record updated');
            return $this->redirect(['index']);
        }
        return $this->render('update', [
            'model' => $model
        ]);
    }

    /**
     * @param int $id
     * @return Response
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }

    /**
     * @return float
     * @throws ForbiddenHttpException
     * @throws UnprocessableEntityHttpException
     */
    public function actionChangePrice()
    {
        if (!Yii::$app->request->isAjax) {
            throw new ForbiddenHttpException;
        }

        $product = Yii::$app->request->post('Product');
        if ($product) {
            $model = $this->findModel(ArrayHelper::getValue($product, 'id'));
            $model->price = ArrayHelper::getValue($product, 'price');
            if ($model->update(true, ['price']) === false) {
                throw new UnprocessableEntityHttpException($model->getFirstError('price'));
            }
            return true;
        }
        return false;
    }

    /**
     * @param int $id
     * @return Product
     * @throws NotFoundHttpException
     */
    private function findModel($id)
    {
        $model = Product::findOne($id);
        if ($model === null) {
            throw new NotFoundHttpException;
        }
        return $model;
    }
}

views/product/_form.php
<?php

/**
 * @var Product $model
 * @var View $this
 */

use app\models\Product;
use app\models\Vendor;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\ActiveForm;

$form = ActiveForm::begin();
echo $form->field($model, 'name');
echo $form->field($model, 'vendor_id')
    ->dropDownList(ArrayHelper::map(Vendor::find()->all(), 'id', 'name'));
echo $form->field($model, 'price');
echo Html::submitButton(Yii::t('app', 'Save'), [
    'class' => 'btn btn-success'
]);
$form->end();

views/product/create.php
<?php

use app\models\Product;
use yii\web\View;

/**
 * @var Product $model
 * @var View $this
 */


$this->title = Yii::t('app', 'Create product');
$this->params['breadcrumbs'][] = [
    'url' => ['index'],
    'label' => Yii::t('app', 'Products list')
];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box box-primary">
    <div class="box-body">
        <?= $this->render('_form', [
            'model' => $model
        ]) ?>
    </div>
</div>

views/product/index.php
<?php

use app\models\Product;
use app\models\Vendor;
use app\models\search\ProductSearch;
use kartik\editable\Editable;
use yii\data\ActiveDataProvider;
use yii\grid\ActionColumn;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var ActiveDataProvider $dataProvider
 * @var ProductSearch $searchModel
 */

$this->title = Yii::t('app', 'Products list');
$this->params['breadcrumbs'][] = $this->title;

?>
<?= Html::a('<i class="fa fa-plus"></i> ' . Yii::t('app', 'Add product'), ['create'], [
    'class' => 'btn btn-success'
]) ?>
<div class="box box-primary" style="margin-top:25px;">
    <div class="box-body">
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                [
                    'attribute' => 'vendor_id',
                    'filter' => ArrayHelper::map(Vendor::find()->all(), 'id', 'name'),
                    'value' => function (Product $model) {
                        return $model->vendor->name;
                    }
                ],
                'name',
                [
                    'attribute' => 'price',
                    'format' => 'raw',
                    'value' => function (Product $model) {
                        return Editable::widget([
                            'name' => 'Product[price]',
                            'additionalData' => [
                                'Product[id]' => $model->primaryKey
                            ],
                            'value' => $model->price,
                            'size'=>'md',
                            'options' => ['class'=>'form-control', 'placeholder'=> Yii::t('app', 'Enter price')],
                            'ajaxSettings' => [
                                'url' => Url::to(['product/change-price']),
                            ]
                        ]);
                    }
                ],
                [
                    'class' => ActionColumn::class,
                    'headerOptions' => [
                        'width' => 50,
                    ],
                    'template' => '{update} {delete}',
                ],
            ],
        ]) ?>
    </div>
</div>

views/product/update.php
<?php

use app\models\Product;
use yii\web\View;

/**
 * @var Product $model
 * @var View $this
 */


$this->title = Yii::t('app', 'Update product');
$this->params['breadcrumbs'][] = [
    'url' => ['index'],
    'label' => Yii::t('app', 'Products list')
];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box box-primary">
    <div class="box-body">
        <?= $this->render('_form', [
            'model' => $model
        ]) ?>
    </div>
</div>